### ISSUE TITLE
Design Mockup

### ISSUE THREAD

**Issue by bchen10** [electiondata/electiondata.github.io#5]
Here is the most recent revision based on our discussion earlier today. A made a few minor changes here, but feel like this is moving in a more actionable direction. 

Things I've changed: 
- Removed the missions section and bumped everything up
- Included a contribute button at the top to place the access and contribute buttons upfront so users will see these call to actions earlier
- For the country cards, I removed the download buttons and put links in that would take someone to the repo in the instance a country has more than one election

If you guys have any additional comments feel free to chime in here. 

![oe_landingpage_v3](https://cloud.githubusercontent.com/assets/15217157/14867994/56cdb098-0c99-11e6-92ac-fc40e0286603.png)

@scisco @felskia @ianschuler @DylanMoriarty

**Comment by scisco** [comment]
@bchen10 this looks really nice and I think addresses the concerns @ianschuler raised in the last meeting.

@bchen10 @DylanMoriarty Let's chat about building the front-end and the framework to use on Monday

**Comment by felskia** [comment]
@bchen10 yeah, really I think it looks good. I would make a few simple tweaks: 
- It looks like there is actually more white space above and below the last block than there is in the election data block. I would just make the spacing in the election data block greater at the top and bottom
- For the actual cards. I think you can make the whole care clickable instead of having the "view data" links. 
- For the cards I would also make the country names bigger or more bold. There isn't much of a hierarchy between the titles and the content. That said you could also make the content a little smaller. 
- Finally, for the cards, it might be nice to see what format is available for them. 
- I would add a "View All Datasets" button at the bottom of the election section just to mock up what it will look like when we get more data. 
- For the area that show the use cases, I think you should add more spacing above and below the main text, essentially making that area slightly bigger. Also, I would add a button for each so that users know what to click to view the details. Maybe "View Use case". Finally use case is two words.
- For the last section, I think adding a main title to the top will help with this. Kind of a "Ready to help?" header.
- Finally for the last section, I wouldn't align the buttons but put them at the end of the content blocks. For contribute it just creates awkward white space. To make it more balanced I think we can play with the text.
- I think we can make the text better but we don't need to necessarily worry about that now. I would just make a note so that we remember to do in, maybe next week.

Maybe make these small changes and post again before you guys start building? Also, you'll for sure need a design for interior pages before you move forward. 

Thanks!

**Comment by bchen10** [comment]
Thanks for your feedback @felskia and @scisco. I've attached the revised mockup here. Let me know if you see anything else that should be addressed; Otherwise, I plan to start building basic page structure this week. 

@DylanMoriarty will be working on internal page mockups this week and plans to meet Wednesday for review with the team (calendar invite forthcoming). 

![oe_landingpage_v4](https://cloud.githubusercontent.com/assets/15217157/14963926/037fcd5c-1074-11e6-86a7-059b26b5c3e1.png)
